#!c:/python36/python.exe

import cgi,cgitb
from os import listdir
from os.path import isfile, join
import time
import dateutil.parser
import datetime
import json
import re
import codecs

cgitb.enable()

def start_page():
	print('Content-type: text/html\n')
	print('''<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
<meta charset="utf-8" />
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta http-equiv="Cache-control: no-cache" content="public">
<meta http-equiv="Pragma: no-cache" content="public">
<title>@norsivaeb tweets</title>
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="shortcut icon" href="/p/scb_16.ico">
<link rel="apple-touch-icon" sizes="180x180" href="/p/scb_180.png">
<link rel="icon" type="image/png" sizes="32x32" href="/p/scb_32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/p/scb_16.png">
<link rel="stylesheet" href="/css/scb.css">

<style media="screen" type="text/css">
	body {
		color: #000000;
		background-color: #FFFFFF;
		font-weight: normal;
		font-family:  Roboto, Helvetica, Arial, sans-serif;
		font-size: 12pt;
		margin: 10px 10px 10px 10px;
		text-align:left;	
	}
	a {
		color: #00f;
		text-decoration: none;
	}
	div.display	{
		background-color: #ddeedd;
		padding: 10px;
		bottom: 10px;
		top: 10px;
		right: 10px;
		left: 200px;
	}
	.entry {
		border-radius:5px 20px 20px 5px;
		display: block;
		max-width: 600px;
		margin: 10px 10px 3px 3px;
		background-color: #BBFFFF;
		padding: 6pt 6pt 6pt 6pt;
		text-align: left;
	}
	.time	{
		font-weight: normal;
		font-family:  Roboto;
		font-size: 10pt;
		display: block;
		font-style: italic;

	}
	ul li, ol li {
		line-height:160%;
	}
	.but {
	  background-color: initial;
	  background-image: linear-gradient(-180deg, #FF7E31, #E62C03);
	  border-radius: 6px;
	  box-shadow: rgba(0, 0, 0, 0.1) 0 2px 4px;
	  color: #FFFFFF;
	  cursor: pointer;
	  display: inline-block;
	  height: 25px;
	  line-height: 25px;
	  outline: 0;
	  overflow: hidden;
	  padding: 0 4px;
	  pointer-events: auto;
	  position: relative;
	  text-align: center;
	  touch-action: manipulation;
	  user-select: none;
	  -webkit-user-select: none;
	  vertical-align: top;
	  white-space: nowrap;
	  width: 30px;
	  z-index: 9;
	  border: 0;
	  transition: box-shadow .2s;
	  font-size: 12pt;
	}
	.but:hover {
		box-shadow: rgba(253, 76, 0, 0.5) 0 3px 8px;
	}
	div.wrapper	{
		margin-left: 50px;
	}
</style>
</head>
<body>
<center>
		''')

def end_page():
	print('''</center></body>\n</html>\n''')
	
def sorted_nicely(_l):
    convert = lambda text: int(text) if text.isdigit() else text
    alphanum_key = lambda key: [convert(c) for c in re.split('([0-9]+)', key)]
    return sorted(_l, key = alphanum_key, reverse=True)

def get_info(_p):
	ls = [l.rstrip() for l in open(_p,'r')]
	for l in ls:
		if l.find('<title>') != -1:
			return re.sub(r'\<.+?\>','',l)
	return 'no info'

start_page()

form = cgi.FieldStorage()

search = '2022'
try:
	search = form['s'].value
except:
	search = '2022'

path_to_profile = '/twitter/norsivaeb/profile_media/986973114377519104-OSd02dFr.png'
path_to_jsonlines = 'D:/somecrazyblogger-org/twitter/norsivaeb/tweet.jl'
path_to_this = '/a/tweets'
user_name = 'NorSivaeb'

print('<h3>@%s‎ T​w​‎eets​‌‎ <img src="%s" width="30" align="middle"/></h3>' % (user_name,path_to_profile)
print('')
years = ['2022','2021','2020','2019','2018']
print('| <a href="/a/tweets?s=2022">2022</a> ')
print('| <a href="/a/tweets?s=2021">2021</a> ')
print('| <a href="/a/tweets?s=2020">2020</a> ')
print('| <a href="/a/tweets?s=2019">2019</a> ')
print('| <a href="/a/tweets?s=2018">2018</a> ')
print('| ')
print('<form style="display: inline" name="search_form" method="GET" action="%s"><input type="text" name="s" value="%s" placeholder="Search text or year"/> <input class="but" type="submit" value="go"/></form>' % (path_to_this,search))
stype = 0
if search in years:
	stype = 1
jf = codecs.open(path_to_jsonlines, encoding='utf-8')
tot = 0
for l in jf:
	j = json.loads(l)
	if stype == 1 and j["created_at"].find(search) == -1:
		continue
#	elif stype == 0 and j["full_text"].find(search) == -1:
	elif stype == 0 and re.search(search,j["full_text"],re.I) is None:
		continue
	try:
		str = ""
		tot += 1
		if j["full_text"].find('RT @') != 0:
			ol = re.sub(r'(https\:\/\/[\w\.\/]+)',r'<a href="\1" target="_blank">&#128279;</a>',j["full_text"])
			print('<div class="entry"><span class="time">%s</span>%s</div>' % (j["created_at"],ol))
			if 'extended_entities' in j:
				if 'media' in j['extended_entities']:
					url = ''
					for jem in j['extended_entities']['media']:
						if 'expanded_url' in jem and 'media_url' in jem:
							v = re.sub(r'https\:\/\/twitter\.com\/%s\/status\/(\d+)\/.+' % (user_name),r'\1',jem['expanded_url'])
							u = re.sub(r'http\:\/\/pbs\.twimg\.com\/media\/([\w\-]+\..+)',r'\1',jem['media_url'])
							url = '/twitter/norsivaeb/tweets_media/%s-%s' % (v,u)
							str += '<a href="%s" target="_blank"><img src="%s" width="600"/></a><br />' % (jem['expanded_url'],url)
		if len(str) > 0:
			print(re.sub(r'\<br \/\>$',r'',str))
	except:
		pass
print('<br /><i>tweets = %i</i>'% (tot))
end_page()

